services: 
  mysql:
    image: mysql:latest
    container_name: school-cafeteria-db
    environment: 
      TZ: 'America/Sao_Paulo'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes: 
  mysql_data:
